version: "3.7"

networks:
  ha-stack:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  pgdata: {}

services:
  runner:
    build:
      context: runner
    image: "alpine/command-runner:local"
    dns: 172.20.0.5
    networks:
      - ha-stack

  coredns:
    image: docker.io/coredns/coredns:1.6.5
    command: -conf /data/Corefile
    volumes:
      - ./coredns/data:/data:ro
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    restart: always
    networks:
      ha-stack:
        ipv4_address: 172.20.0.5

  db:
    image: postgres:12.0-alpine
    restart: always
    dns: 172.20.0.5
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - ha-stack

  keycloak-a:
    depends_on:
      - db
    image: docker.io/jboss/keycloak:7.0.1
    dns: 172.20.0.5
    networks:
      ha-stack:
        ipv4_address: 172.20.0.30
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: keycloakdb
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      CACHE_OWNERS_COUNT: 2
      CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2
      JGROUPS_TRANSPORT_STACK: tcp
      JGROUPS_DISCOVERY_PROTOCOL: dns.DNS_PING
      JGROUPS_DISCOVERY_PROPERTIES: dns_query=keycloak.service-discovery.local
    ports:
      - 8080:8080

  keycloak-b:
    depends_on:
      - db
    image: docker.io/jboss/keycloak:7.0.1
    dns: 172.20.0.5
    networks:
      ha-stack:
        ipv4_address: 172.20.0.31
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: keycloakdb
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      CACHE_OWNERS_COUNT: 2
      CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2
      KEYCLOAK_PASSWORD: admin
      JGROUPS_TRANSPORT_STACK: tcp
      JGROUPS_DISCOVERY_PROTOCOL: dns.DNS_PING
      JGROUPS_DISCOVERY_PROPERTIES: dns_query=keycloak.service-discovery.local
    ports:
      - 9090:8080
